### ISSUE TITLE
Souce code of Baseline models

### ISSUE THREAD

**Issue by yanyou426** [pdlan/OSCAR#8]
Hello! Do you have plans to upload source code of the baseline models (especially the 'BinaryAI')? Thanks a lot.

**Comment by pdlan** [comment]
Sorry that I finished my internship at Microsoft last year so I am not permitted to release any more code related to this project since then. Also, for the "BinaryAI" baseline, the prediction is done by a web API provided by Tencent, which may have changed by a lot since then, so the code and results are unlikely to be the same.

**Comment by yanyou426** [comment]
Thanks a lot!
